# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='货源分类')),
            ],
            options={
                'verbose_name': '货源分类',
                'verbose_name_plural': '货源分类',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='性别分类')),
            ],
            options={
                'verbose_name': '性别分类',
                'verbose_name_plural': '性别分类',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='产品名称')),
                ('delivery_time', models.CharField(default='3天', max_length=20, verbose_name='送货时间')),
                ('price', models.FloatField(max_length=20, verbose_name='商品价格')),
                ('ends_time', models.DateTimeField(verbose_name='下架时间')),
                ('desc', models.CharField(default='本商品占无简介', max_length=1024, verbose_name='商品简介')),
                ('images', models.ImageField(null=True, upload_to='')),
                ('featured', models.ManyToManyField(to='items_detail.Featured')),
                ('gender', models.ManyToManyField(to='items_detail.Gender')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='类型分类')),
            ],
            options={
                'verbose_name': '类型分类',
                'verbose_name_plural': '类型分类',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ManyToManyField(to='items_detail.Type'),
        ),
    ]
