# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_detail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(default='黑色', max_length=10, verbose_name='颜色'),
        ),
    ]
