# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items_detail', '0003_auto_20181103_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tail',
            field=models.FileField(null=True, upload_to='vedio'),
        ),
    ]
